swagger: '2.0'
info:
  version: '1.0'
  title: "PadelHub"
  description: API per gestire un sistema di prenotazioni di partite di padel.
host: padelhub-back.onrender.com
basePath: /api/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /authentication:
    x-summary: Autenticazione
    post: 
      summary: Fornisce l'autenticazione alla piattaforma
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      responses:
        200:
          description: Dati inseriti validi, risposta valida
          schema:
            $ref: '#/definitions/LoginApproved'
definitions:
  LoginRequest:
    title: Login Request
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password
    example:
      email: matteo@email.com
      password: password
  LoginApproved:
    title: Login Approved
    type: object
    properties:
      success:
        type: boolean
      message: 
        type: string
      token: 
        type: string
      dati:
        type: object
        properties:
          tipoAccount:
            type: string
          email:
            type: string
          nome:
            type: string
    example: 
      success: true
      message: Autenticazione completata con successo
      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aXBvQWNjb3VudCI6Ikdpb2NhdG9yZSIsImVtYWlsIjoibWF0dGVvQGVtYWlsLmNvbSIsIm5vbWUiOiJNYXR0ZW8iLCJpYXQiOjE2ODM2NTAwMTIsImV4cCI6MTY4MzgyMjgxMn0.rzU6tIfELQbQlRmoDWJj1i5VMurGIr0r8IMiz-0Yuo4
      dati:
        tipoAccount: Giocatore
        email: email@email.com
        nome: Matteo
