name: Node.js CI
run-name: Node.js testing
on:
  push: 
    branches: [ main, develop ]
  workflow_dispatch:
    branches: [ main, develop ]
jobs:
  test-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
