name: deploy-test
run-name: ${{ github.actor }} is testing ci
on: workflow_dispatch
jobs:
  testing-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm run dev
